version: '3.4'
x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file
services:
  web-spa:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=mongodb://localhost/museum-bgpz
      - Database=museum-bgpz
    ports:
      - 80:80
    logging: *default-logging