version: '3.4'
x-logging:
  &default-logging
  options:
    max-size: "10m"
    max-file: "5"
  driver: json-file
services:
  web-spa:
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionString=mongodb://museum-bgpz:museum-bgpz1@bl-dck-21.it.beloil.by:27027/museum-bgpz
      - Database=museum-bgpz
      - IdentityUrl=https://dev.it.beloil.by/identity
      - IdentityUrlExternal=https://dev.beloil.by/identity
    ports:
      - 8078:80
    logging: *default-logging
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=MUSEUM-BGPZ]
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == worker]