version: '3.4'

services:
  web-spa:
    image: ${DOCKERREGISTRY:-docker.it.beloil.by/}museum/museum-bgpz:${TAG_WEBSPA:-latest}
    build:
      context: .
      dockerfile: ./src/Web/Web.Spa/Dockerfile